name: nbeats
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=hd77b12b_0
  - absl-py=1.4.0=py311haa95532_0
  - aiohttp=3.8.3=py311h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - ansicon=1.89.0=py311h1ea47a8_6
  - anyio=3.5.0=py311haa95532_0
  - arrow=1.2.3=py311haa95532_1
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=py311haa95532_0
  - attrs=22.1.0=py311haa95532_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backoff=2.2.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=py311haa95532_0
  - blas=1.0=mkl
  - blessed=1.19.1=pyh95a074a_2
  - blinker=1.4=py311haa95532_0
  - bottleneck=1.3.5=py311h5bb9823_0
  - brotlipy=0.7.0=py311h2bbff1b_1002
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.19.0=h2bbff1b_0
  - ca-certificates=2023.05.30=haa95532_0
  - cachecontrol=0.13.1=pyhd8ed1ab_0
  - cachecontrol-with-filecache=0.13.1=pyhd8ed1ab_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.7.22=py311haa95532_0
  - cffi=1.15.1=py311h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cleo=2.0.1=py311haa95532_0
  - click=8.0.4=py311haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - crashtest=0.4.1=py311haa95532_0
  - croniter=1.3.7=py311haa95532_0
  - cryptography=41.0.2=py311hac1b9e3_0
  - cuda-cccl=12.0.90=h57928b3_1
  - cuda-cccl-impl=2.0.1=h57928b3_1
  - cuda-cccl_win-64=12.0.90=h57928b3_1
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.0=hffde075_2
  - dateutils=0.6.12=py_0
  - debugpy=1.6.8=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=6.3.1=pyhd8ed1ab_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - dulwich=0.21.3=py311h2bbff1b_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fastapi=0.103.0=pyhd8ed1ab_0
  - filelock=3.12.3=pyhd8ed1ab_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py311h2bbff1b_0
  - fsspec=2023.4.0=py311haa95532_0
  - giflib=5.2.1=h8cc25b3_3
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.5.2=py311haa95532_0
  - grpc-cpp=1.48.2=hfe90ff0_1
  - grpcio=1.48.2=py311hfe90ff0_1
  - h11=0.12.0=pyhd3eb1b0_0
  - idna=3.4=py311haa95532_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.1=pyh6817e22_0
  - ipython=8.14.0=pyh08f2357_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=py311haa95532_0
  - jinxed=1.2.0=pyh95a074a_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema=4.17.3=py311haa95532_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h1ea47a8_0
  - keyring=24.2.0=py311h1ea47a8_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.1.50=h63175ca_0
  - libcurand-dev=10.3.1.50=h63175ca_0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.43.0=hcfcfb64_0
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libzlib=1.2.13=hcfcfb64_5
  - lightning=2.0.8=pyhd8ed1ab_0
  - lightning-cloud=0.5.37=pyhd8ed1ab_0
  - lightning-utilities=0.7.1=py311haa95532_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.1=py311haa95532_0
  - markdown-it-py=2.2.0=py311haa95532_1
  - markupsafe=2.1.1=py311h2bbff1b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.6=py311hf62ec03_1
  - mkl_random=1.2.2=py311hf62ec03_1
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpmath=1.3.0=py311haa95532_0
  - msgpack-python=1.0.3=py311h59b6b97_0
  - multidict=6.0.2=py311h2bbff1b_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=py311haa95532_0
  - numexpr=2.8.4=py311h1fcbade_1
  - numpy=1.25.2=py311hdab7c0b_0
  - numpy-base=1.25.2=py311hd01c5d8_0
  - oauthlib=3.2.2=py311haa95532_0
  - openssl=3.1.2=hcfcfb64_0
  - ordered-set=4.1.0=py311haa95532_0
  - orjson=3.8.8=py311h2bbff1b_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py311hf62ec03_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311hd77b12b_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pkginfo=1.9.6=py311haa95532_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - poetry=1.6.1=win_pyh7428d3b_0
  - poetry-core=1.7.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.5.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=3.20.3=py311hd77b12b_0
  - psutil=5.9.5=py311ha68e1ae_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.8=py311h2bbff1b_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.4.0=py311haa95532_0
  - pyopenssl=23.2.0=py311haa95532_0
  - pyproject_hooks=1.0.0=py311haa95532_0
  - pyrsistent=0.18.0=py311h2bbff1b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=h2628c8c_0_cpython
  - python-build=0.10.0=py311haa95532_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-multipart=0.0.6=py311haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=3_cp311
  - pytorch=2.0.1=py3.11_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-lightning=2.0.3=py311haa95532_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py311haa95532_0
  - pywin32=304=py311h12c1d0e_2
  - pywin32-ctypes=0.2.0=py311haa95532_1000
  - pyyaml=6.0=py311h2bbff1b_1
  - pyzmq=25.1.1=py311h7b3f143_0
  - rapidfuzz=2.13.7=py311hea22821_0
  - re2=2022.04.01=hd77b12b_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - requests=2.31.0=py311haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - requests-toolbelt=1.0.0=py311haa95532_0
  - rich=13.3.5=py311haa95532_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=68.1.2=pyhd8ed1ab_0
  - shellingham=1.5.0=py311haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py311haa95532_1
  - soupsieve=2.4=py311haa95532_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - starlette=0.27.0=py311haa95532_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - sympy=1.11.1=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311haa95532_0
  - tk=8.6.12=h8ffe710_0
  - tomli=2.0.1=py311haa95532_0
  - tomlkit=0.12.1=pyha770c72_0
  - torchmetrics=0.11.4=py311h746a85d_1
  - tornado=6.3.3=py311ha68e1ae_0
  - tqdm=4.65.0=py311h746a85d_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - trove-classifiers=2023.3.9=py311haa95532_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.16=py311haa95532_0
  - uvicorn=0.20.0=py311haa95532_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hfdfe4a8_17
  - virtualenv=20.24.4=pyhd8ed1ab_0
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - websocket-client=0.58.0=py311haa95532_4
  - websockets=10.4=py311h2bbff1b_1
  - werkzeug=2.2.3=py311haa95532_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=he774522_0
  - yarl=1.8.1=py311h2bbff1b_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zstd=1.4.9=h19a0ad4_0
  - pip:
      - torchaudio==2.0.2
      - torchvision==0.15.2
prefix: C:\Users\DanielByrne\AppData\Local\miniconda3\envs\nbeats
